;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "bot-skill")
(def path ".")
(def version "0.1.4")
(def tag "0.1.4")
(def generated-at "2020-07-15T00:49:10Z")
