 ;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "bot-skill")
(def path ".")
(def version "0.1.5")
(def tag "0.1.5")
(def generated-at "2020-07-15T01:08:25Z")
